# Site settings
title: Arkadiusz Jaskólski
description: 'dev'
url: 'http://czogori.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Arkadiusz Jaskólski'
  email: arek.jaskolski@gmail.com
  twitter_username: arekjaskolski
  github_username:  czogori

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
